/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kingstar.messaging.api;

public final class APIResult {
  public final static APIResult SUCCESS = new APIResult("SUCCESS", KSKingMQAPIJNI.SUCCESS_get());
  public final static APIResult CONFIG_FILE_LOAD_FAILED = new APIResult("CONFIG_FILE_LOAD_FAILED", KSKingMQAPIJNI.CONFIG_FILE_LOAD_FAILED_get());
  public final static APIResult LOG_INIT_FAILED = new APIResult("LOG_INIT_FAILED", KSKingMQAPIJNI.LOG_INIT_FAILED_get());
  public final static APIResult TRADE_API_INIT_FAILED = new APIResult("TRADE_API_INIT_FAILED", KSKingMQAPIJNI.TRADE_API_INIT_FAILED_get());
  public final static APIResult KFTS_API_CREATE_FAILED = new APIResult("KFTS_API_CREATE_FAILED", KSKingMQAPIJNI.KFTS_API_CREATE_FAILED_get());
  public final static APIResult KFTS_API_SET_OPT_FAILED = new APIResult("KFTS_API_SET_OPT_FAILED", KSKingMQAPIJNI.KFTS_API_SET_OPT_FAILED_get());
  public final static APIResult KFTS_API_REG_FRONT_FAILED = new APIResult("KFTS_API_REG_FRONT_FAILED", KSKingMQAPIJNI.KFTS_API_REG_FRONT_FAILED_get());
  public final static APIResult NEW_API_GROUP_FAILED = new APIResult("NEW_API_GROUP_FAILED", KSKingMQAPIJNI.NEW_API_GROUP_FAILED_get());
  public final static APIResult FRONT_CONFIG_NUM_ERR = new APIResult("FRONT_CONFIG_NUM_ERR", KSKingMQAPIJNI.FRONT_CONFIG_NUM_ERR_get());
  public final static APIResult COMM_PARA_IS_NULL = new APIResult("COMM_PARA_IS_NULL", KSKingMQAPIJNI.COMM_PARA_IS_NULL_get());
  public final static APIResult CREATE_TO_MANY_TRADE_API = new APIResult("CREATE_TO_MANY_TRADE_API", KSKingMQAPIJNI.CREATE_TO_MANY_TRADE_API_get());
  public final static APIResult TRADE_API_NOT_ALL_LOGINED = new APIResult("TRADE_API_NOT_ALL_LOGINED", KSKingMQAPIJNI.TRADE_API_NOT_ALL_LOGINED_get());
  public final static APIResult MAIN_API_START_LOGIN_FAILED = new APIResult("MAIN_API_START_LOGIN_FAILED", KSKingMQAPIJNI.MAIN_API_START_LOGIN_FAILED_get());
  public final static APIResult TRADE_API_START_LOGIN_FAILED = new APIResult("TRADE_API_START_LOGIN_FAILED", KSKingMQAPIJNI.TRADE_API_START_LOGIN_FAILED_get());
  public final static APIResult PUSH_API_START_LOGIN_FAILED = new APIResult("PUSH_API_START_LOGIN_FAILED", KSKingMQAPIJNI.PUSH_API_START_LOGIN_FAILED_get());
  public final static APIResult SUBSCRIBE_TOPIC_FAILED = new APIResult("SUBSCRIBE_TOPIC_FAILED", KSKingMQAPIJNI.SUBSCRIBE_TOPIC_FAILED_get());
  public final static APIResult MAIN_API_NOT_RELAY_LOGIN = new APIResult("MAIN_API_NOT_RELAY_LOGIN", KSKingMQAPIJNI.MAIN_API_NOT_RELAY_LOGIN_get());
  public final static APIResult NEW_OBJ_RETURN_NULL = new APIResult("NEW_OBJ_RETURN_NULL", KSKingMQAPIJNI.NEW_OBJ_RETURN_NULL_get());
  public final static APIResult RESUME_FROM_FLOW_FILE_FAILED = new APIResult("RESUME_FROM_FLOW_FILE_FAILED", KSKingMQAPIJNI.RESUME_FROM_FLOW_FILE_FAILED_get());
  public final static APIResult PUBLIC_FLOW_RESUME_TIMEOUT = new APIResult("PUBLIC_FLOW_RESUME_TIMEOUT", KSKingMQAPIJNI.PUBLIC_FLOW_RESUME_TIMEOUT_get());
  public final static APIResult OPEN_FLOW_FILE_FAILED = new APIResult("OPEN_FLOW_FILE_FAILED", KSKingMQAPIJNI.OPEN_FLOW_FILE_FAILED_get());
  public final static APIResult CREATE_MDB_ERROR = new APIResult("CREATE_MDB_ERROR", KSKingMQAPIJNI.CREATE_MDB_ERROR_get());
  public final static APIResult GET_SUBSRIBE_FLOW_ERROR = new APIResult("GET_SUBSRIBE_FLOW_ERROR", KSKingMQAPIJNI.GET_SUBSRIBE_FLOW_ERROR_get());
  public final static APIResult SUBSCRIBE_TOPIC_COUNT_IS_ZERO = new APIResult("SUBSCRIBE_TOPIC_COUNT_IS_ZERO", KSKingMQAPIJNI.SUBSCRIBE_TOPIC_COUNT_IS_ZERO_get());
  public final static APIResult NO_ACTIVE_PUSH_API = new APIResult("NO_ACTIVE_PUSH_API", KSKingMQAPIJNI.NO_ACTIVE_PUSH_API_get());
  public final static APIResult NO_ACTIVE_TRADE_API = new APIResult("NO_ACTIVE_TRADE_API", KSKingMQAPIJNI.NO_ACTIVE_TRADE_API_get());
  public final static APIResult NO_ACTIVE_MAIN_API = new APIResult("NO_ACTIVE_MAIN_API", KSKingMQAPIJNI.NO_ACTIVE_MAIN_API_get());
  public final static APIResult USER_LOGIN_FAILED = new APIResult("USER_LOGIN_FAILED", KSKingMQAPIJNI.USER_LOGIN_FAILED_get());
  public final static APIResult GENERATE_TOKEN_ERR = new APIResult("GENERATE_TOKEN_ERR", KSKingMQAPIJNI.GENERATE_TOKEN_ERR_get());
  public final static APIResult TOKEN_STRING_ARRAY_ILLEGAL = new APIResult("TOKEN_STRING_ARRAY_ILLEGAL", KSKingMQAPIJNI.TOKEN_STRING_ARRAY_ILLEGAL_get());
  public final static APIResult APP_ID_IN_TOKEN_IS_ERR = new APIResult("APP_ID_IN_TOKEN_IS_ERR", KSKingMQAPIJNI.APP_ID_IN_TOKEN_IS_ERR_get());
  public final static APIResult TOKEN_CHECK_FAILED = new APIResult("TOKEN_CHECK_FAILED", KSKingMQAPIJNI.TOKEN_CHECK_FAILED_get());
  public final static APIResult PACK_ERROR = new APIResult("PACK_ERROR", KSKingMQAPIJNI.PACK_ERROR_get());
  public final static APIResult ORDER_FAIL_BY_KFTS = new APIResult("ORDER_FAIL_BY_KFTS", KSKingMQAPIJNI.ORDER_FAIL_BY_KFTS_get());
  public final static APIResult LOGOUT_FAILED = new APIResult("LOGOUT_FAILED", KSKingMQAPIJNI.LOGOUT_FAILED_get());
  public final static APIResult INVALID_ORDER_COUNT = new APIResult("INVALID_ORDER_COUNT", KSKingMQAPIJNI.INVALID_ORDER_COUNT_get());
  public final static APIResult CALL_QUERY_SERVICE_FAILED = new APIResult("CALL_QUERY_SERVICE_FAILED", KSKingMQAPIJNI.CALL_QUERY_SERVICE_FAILED_get());
  public final static APIResult CAN_NOT_FIND_CELL = new APIResult("CAN_NOT_FIND_CELL", KSKingMQAPIJNI.CAN_NOT_FIND_CELL_get());
  public final static APIResult CAN_NOT_FIND_CUST_NO = new APIResult("CAN_NOT_FIND_CUST_NO", KSKingMQAPIJNI.CAN_NOT_FIND_CUST_NO_get());
  public final static APIResult USER_TYPE_ERROR = new APIResult("USER_TYPE_ERROR", KSKingMQAPIJNI.USER_TYPE_ERROR_get());
  public final static APIResult UNPACK_ERROR = new APIResult("UNPACK_ERROR", KSKingMQAPIJNI.UNPACK_ERROR_get());
  public final static APIResult NETWORK_ERROR = new APIResult("NETWORK_ERROR", KSKingMQAPIJNI.NETWORK_ERROR_get());
  public final static APIResult INVALID_ACCOUNT = new APIResult("INVALID_ACCOUNT", KSKingMQAPIJNI.INVALID_ACCOUNT_get());
  public final static APIResult INVALID_IP = new APIResult("INVALID_IP", KSKingMQAPIJNI.INVALID_IP_get());
  public final static APIResult INVALID_MAC = new APIResult("INVALID_MAC", KSKingMQAPIJNI.INVALID_MAC_get());
  public final static APIResult LICENSE_EXPIRED = new APIResult("LICENSE_EXPIRED", KSKingMQAPIJNI.LICENSE_EXPIRED_get());
  public final static APIResult OLD_VERSION = new APIResult("OLD_VERSION", KSKingMQAPIJNI.OLD_VERSION_get());
  public final static APIResult MD5_CHECK_FAILURE = new APIResult("MD5_CHECK_FAILURE", KSKingMQAPIJNI.MD5_CHECK_FAILURE_get());
  public final static APIResult GENERAL_FAILURE = new APIResult("GENERAL_FAILURE", KSKingMQAPIJNI.GENERAL_FAILURE_get());
  public final static APIResult RELAY_CONFIG_EMPTY = new APIResult("RELAY_CONFIG_EMPTY", KSKingMQAPIJNI.RELAY_CONFIG_EMPTY_get());
  public final static APIResult INVALID_FRONT_TYPE = new APIResult("INVALID_FRONT_TYPE", KSKingMQAPIJNI.INVALID_FRONT_TYPE_get());
  public final static APIResult INVALID_PARA = new APIResult("INVALID_PARA", KSKingMQAPIJNI.INVALID_PARA_get());
  public final static APIResult NO_ACTIVE_QUERY_API = new APIResult("NO_ACTIVE_QUERY_API", KSKingMQAPIJNI.NO_ACTIVE_QUERY_API_get());
  public final static APIResult USER_LOGIN_AUTH_FAIL = new APIResult("USER_LOGIN_AUTH_FAIL", KSKingMQAPIJNI.USER_LOGIN_AUTH_FAIL_get());
  public final static APIResult NO_SOURCE_TERMINAL_INFO = new APIResult("NO_SOURCE_TERMINAL_INFO", KSKingMQAPIJNI.NO_SOURCE_TERMINAL_INFO_get());
  public final static APIResult STREAM_LIMITTED = new APIResult("STREAM_LIMITTED", KSKingMQAPIJNI.STREAM_LIMITTED_get());
  public final static APIResult INVALID_BUSINESS_TYPE = new APIResult("INVALID_BUSINESS_TYPE", KSKingMQAPIJNI.INVALID_BUSINESS_TYPE_get());
  public final static APIResult NOT_FIND_SEC_INFO = new APIResult("NOT_FIND_SEC_INFO", KSKingMQAPIJNI.NOT_FIND_SEC_INFO_get());
  public final static APIResult NOT_FIND_IP_AND_MAC = new APIResult("NOT_FIND_IP_AND_MAC", KSKingMQAPIJNI.NOT_FIND_IP_AND_MAC_get());
  public final static APIResult SEND_MESSAGE_FAILED = new APIResult("SEND_MESSAGE_FAILED", KSKingMQAPIJNI.SEND_MESSAGE_FAILED_get());
  public final static APIResult NOT_EXIST_MD5_INFO = new APIResult("NOT_EXIST_MD5_INFO", KSKingMQAPIJNI.NOT_EXIST_MD5_INFO_get());
  public final static APIResult SUBSCRIBE_TOPIC_ERROR = new APIResult("SUBSCRIBE_TOPIC_ERROR", KSKingMQAPIJNI.SUBSCRIBE_TOPIC_ERROR_get());
  public final static APIResult API_RESULT_END = new APIResult("API_RESULT_END");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static APIResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + APIResult.class + " with value " + swigValue);
  }

  private APIResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private APIResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private APIResult(String swigName, APIResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static APIResult[] swigValues = { SUCCESS, CONFIG_FILE_LOAD_FAILED, LOG_INIT_FAILED, TRADE_API_INIT_FAILED, KFTS_API_CREATE_FAILED, KFTS_API_SET_OPT_FAILED, KFTS_API_REG_FRONT_FAILED, NEW_API_GROUP_FAILED, FRONT_CONFIG_NUM_ERR, COMM_PARA_IS_NULL, CREATE_TO_MANY_TRADE_API, TRADE_API_NOT_ALL_LOGINED, MAIN_API_START_LOGIN_FAILED, TRADE_API_START_LOGIN_FAILED, PUSH_API_START_LOGIN_FAILED, SUBSCRIBE_TOPIC_FAILED, MAIN_API_NOT_RELAY_LOGIN, NEW_OBJ_RETURN_NULL, RESUME_FROM_FLOW_FILE_FAILED, PUBLIC_FLOW_RESUME_TIMEOUT, OPEN_FLOW_FILE_FAILED, CREATE_MDB_ERROR, GET_SUBSRIBE_FLOW_ERROR, SUBSCRIBE_TOPIC_COUNT_IS_ZERO, NO_ACTIVE_PUSH_API, NO_ACTIVE_TRADE_API, NO_ACTIVE_MAIN_API, USER_LOGIN_FAILED, GENERATE_TOKEN_ERR, TOKEN_STRING_ARRAY_ILLEGAL, APP_ID_IN_TOKEN_IS_ERR, TOKEN_CHECK_FAILED, PACK_ERROR, ORDER_FAIL_BY_KFTS, LOGOUT_FAILED, INVALID_ORDER_COUNT, CALL_QUERY_SERVICE_FAILED, CAN_NOT_FIND_CELL, CAN_NOT_FIND_CUST_NO, USER_TYPE_ERROR, UNPACK_ERROR, NETWORK_ERROR, INVALID_ACCOUNT, INVALID_IP, INVALID_MAC, LICENSE_EXPIRED, OLD_VERSION, MD5_CHECK_FAILURE, GENERAL_FAILURE, RELAY_CONFIG_EMPTY, INVALID_FRONT_TYPE, INVALID_PARA, NO_ACTIVE_QUERY_API, USER_LOGIN_AUTH_FAIL, NO_SOURCE_TERMINAL_INFO, STREAM_LIMITTED, INVALID_BUSINESS_TYPE, NOT_FIND_SEC_INFO, NOT_FIND_IP_AND_MAC, SEND_MESSAGE_FAILED, NOT_EXIST_MD5_INFO, SUBSCRIBE_TOPIC_ERROR, API_RESULT_END };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

