/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kingstar.messaging.api;

public interface KSKingMQAPIConstants {
  public final static int EMPTY_ROW = KSKingMQAPIJNI.EMPTY_ROW_get();
  public final static int EMPTY_ID = KSKingMQAPIJNI.EMPTY_ID_get();
  public final static int EMPTY_NO = KSKingMQAPIJNI.EMPTY_NO_get();
  public final static int API_ERROR_CODE_BASE = KSKingMQAPIJNI.API_ERROR_CODE_BASE_get();
}
