/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kingstar.messaging.api;

public class QueueType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QueueType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QueueType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KSKingMQAPIJNI.delete_QueueType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQueue(String value) {
    KSKingMQAPIJNI.QueueType_queue_set(swigCPtr, this, value);
  }

  public String getQueue() {
    return KSKingMQAPIJNI.QueueType_queue_get(swigCPtr, this);
  }

  public void setBindingKey(String value) {
    KSKingMQAPIJNI.QueueType_bindingKey_set(swigCPtr, this, value);
  }

  public String getBindingKey() {
    return KSKingMQAPIJNI.QueueType_bindingKey_get(swigCPtr, this);
  }

  public void setOffset(int value) {
    KSKingMQAPIJNI.QueueType_offset_set(swigCPtr, this, value);
  }

  public int getOffset() {
    return KSKingMQAPIJNI.QueueType_offset_get(swigCPtr, this);
  }

  public void setDurable(int value) {
    KSKingMQAPIJNI.QueueType_durable_set(swigCPtr, this, value);
  }

  public int getDurable() {
    return KSKingMQAPIJNI.QueueType_durable_get(swigCPtr, this);
  }

  public QueueType() {
    this(KSKingMQAPIJNI.new_QueueType(), true);
  }

}
