/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kingstar.messaging.api;

public final class ReConnectStatus {
  public final static ReConnectStatus ReConnectFail = new ReConnectStatus("ReConnectFail", KSKingMQAPIJNI.ReConnectStatus_ReConnectFail_get());
  public final static ReConnectStatus ReConnecting = new ReConnectStatus("ReConnecting", KSKingMQAPIJNI.ReConnectStatus_ReConnecting_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ReConnectStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ReConnectStatus.class + " with value " + swigValue);
  }

  private ReConnectStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ReConnectStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ReConnectStatus(String swigName, ReConnectStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ReConnectStatus[] swigValues = { ReConnectFail, ReConnecting };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

