/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kingstar.messaging.api;

public class ReqSubscribeField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ReqSubscribeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReqSubscribeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KSKingMQAPIJNI.delete_ReqSubscribeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCnt(int value) {
    KSKingMQAPIJNI.ReqSubscribeField_cnt_set(swigCPtr, this, value);
  }

  public int getCnt() {
    return KSKingMQAPIJNI.ReqSubscribeField_cnt_get(swigCPtr, this);
  }

  public void setElems(QueueType value) {
    KSKingMQAPIJNI.ReqSubscribeField_elems_set(swigCPtr, this, QueueType.getCPtr(value), value);
  }

  public QueueType getElems() {
    long cPtr = KSKingMQAPIJNI.ReqSubscribeField_elems_get(swigCPtr, this);
    return (cPtr == 0) ? null : new QueueType(cPtr, false);
  }

  public ReqSubscribeField() {
    this(KSKingMQAPIJNI.new_ReqSubscribeField(), true);
  }

}
